/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import utils.Graphics;

/**
 *
 * @author TESDA
 */
public class PaintFrame extends javax.swing.JFrame {

    /**
     * Creates new form PaintFrame
     */
    private Color color = Color.BLACK;
    BufferedImage[] images = new BufferedImage[5];
    BufferedImage image;
    Graphics2D graphics;
    public PaintFrame() {
        initComponents();
        Graphics.setToCenter(this);
        image = new BufferedImage(paintPanel.getWidth(), paintPanel.getHeight(),BufferedImage.OPAQUE);
        graphics = image.createGraphics();
        graphics.setBackground(Color.WHITE);
        graphics.fillRect(0, 0, paintPanel.getWidth(), paintPanel.getHeight());
        graphics = image.createGraphics();
        graphics.setPaint(color);
        updateImage();
        
        ButtonGroup group = new ButtonGroup();
        group.add(eraser);
        group.add(pencil);
        group.add(line);
        group.add(eclipse);
        group.add(rectangle);
        group.add(text);
        jPanel2.setVisible(false);
  
        ChangeListener cl = new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
                if(eclipse.isSelected() || rectangle.isSelected()){
                    jPanel2.setVisible(true);
                }else{
                    jPanel2.setVisible(false);
                }
            }
        };
        eclipse.addChangeListener(cl);
        rectangle.addChangeListener(cl);
        
        ButtonGroup group2 = new ButtonGroup();
        group2.add(fill);
        group2.add(outline);
        size.setValue(20);
        onTop.setSelected(false);
        sizeStateChanged(null);
    }

    public final void updateImage(){
        ImageIcon ic = new ImageIcon(image);
        paintPanel.setIcon(ic);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fontFormat = new javax.swing.JDialog();
        font_name = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        sizes_combo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        italic_font = new javax.swing.JCheckBox();
        bold_font = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        preview_text = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        text_value = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        paintPanel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        xP = new javax.swing.JLabel();
        yP = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pencil = new javax.swing.JRadioButton();
        eraser = new javax.swing.JRadioButton();
        line = new javax.swing.JRadioButton();
        eclipse = new javax.swing.JRadioButton();
        rectangle = new javax.swing.JRadioButton();
        text = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        fill = new javax.swing.JRadioButton();
        outline = new javax.swing.JRadioButton();
        clear_button = new javax.swing.JButton();
        xPos = new javax.swing.JTextField();
        yPos = new javax.swing.JTextField();
        size = new javax.swing.JSlider();
        penSize = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        save_as = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        clear = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        onTop = new javax.swing.JCheckBoxMenuItem();

        fontFormat.setTitle("Insert Text");
        fontFormat.setModal(true);
        fontFormat.setResizable(false);

        GraphicsEnvironment e = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Font[] fonts = e.getAllFonts();
        String []fontNames = new String[fonts.length];
        for(int i=0;i<fonts.length;i++){
            fontNames[i] = fonts[i].getFontName();
        }
        font_name.setModel(new javax.swing.DefaultComboBoxModel(fontNames));
        font_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                font_nameActionPerformed(evt);
            }
        });

        jLabel2.setText("Font:");

        String size_l[] = new String[40];
        for(int i=0;i<size_l.length;i++){
            size_l[i] = (i+8)+"";
        }
        sizes_combo.setModel(new javax.swing.DefaultComboBoxModel(size_l));
        sizes_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizes_comboActionPerformed(evt);
            }
        });
        sizes_combo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                sizes_comboInputMethodTextChanged(evt);
            }
        });

        jLabel5.setText("Enter Text:");

        italic_font.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        italic_font.setText("Italic");
        italic_font.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                italic_fontActionPerformed(evt);
            }
        });

        bold_font.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bold_font.setText("Bold");
        bold_font.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bold_fontActionPerformed(evt);
            }
        });

        jLabel4.setText("px");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setToolTipText("");

        jLabel6.setText("Preview");

        preview_text.setText("(preview)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(preview_text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(preview_text)
                .addGap(0, 75, Short.MAX_VALUE))
        );

        jToggleButton1.setText("Ok");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });

        jToggleButton2.setText("Cancel");

        text_value.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_valueKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout fontFormatLayout = new javax.swing.GroupLayout(fontFormat.getContentPane());
        fontFormat.getContentPane().setLayout(fontFormatLayout);
        fontFormatLayout.setHorizontalGroup(
            fontFormatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fontFormatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fontFormatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fontFormatLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2))
                    .addGroup(fontFormatLayout.createSequentialGroup()
                        .addGroup(fontFormatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(fontFormatLayout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fontFormatLayout.createSequentialGroup()
                                .addGroup(fontFormatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(fontFormatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(fontFormatLayout.createSequentialGroup()
                                        .addComponent(italic_font)
                                        .addGap(18, 18, 18)
                                        .addComponent(bold_font))
                                    .addGroup(fontFormatLayout.createSequentialGroup()
                                        .addComponent(font_name, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sizes_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(fontFormatLayout.createSequentialGroup()
                                        .addComponent(text_value)
                                        .addGap(2, 2, 2)))))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        fontFormatLayout.setVerticalGroup(
            fontFormatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fontFormatLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(fontFormatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(font_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizes_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fontFormatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(italic_font)
                    .addComponent(bold_font))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fontFormatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fontFormatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addGap(8, 8, 8))
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Paint");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        paintPanel.setBackground(new java.awt.Color(255, 255, 255));
        paintPanel.setForeground(new java.awt.Color(255, 153, 0));
        paintPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        paintPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        paintPanel.setOpaque(true);
        paintPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paintPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paintPanelMouseEntered(evt);
            }
        });
        paintPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                paintPanelMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                paintPanelMouseMoved(evt);
            }
        });

        colorLabel.setBackground(new java.awt.Color(0, 0, 0));
        colorLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        colorLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        colorLabel.setOpaque(true);
        colorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorLabelMouseClicked(evt);
            }
        });

        jLabel3.setText("color:");

        xP.setText("x:");

        yP.setText("y:");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pencil.setSelected(true);
        pencil.setText("pencil");

        eraser.setText("eraser");

        line.setText("line");

        eclipse.setText("eclipse");

        rectangle.setText("rectangle");

        text.setText("text");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pencil)
                    .addComponent(eraser)
                    .addComponent(line)
                    .addComponent(eclipse)
                    .addComponent(rectangle)
                    .addComponent(text))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eraser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pencil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(line)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eclipse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rectangle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                .addComponent(text))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fill.setSelected(true);
        fill.setText("fill");

        outline.setText("outline");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fill)
                        .addComponent(outline))
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(fill)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(outline)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        clear_button.setText("clear");
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });

        xPos.setEditable(false);

        yPos.setEditable(false);

        size.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sizeStateChanged(evt);
            }
        });

        penSize.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sizeLabel.setEditable(false);

        jLabel1.setText("px");

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("open");
        jMenu1.add(jMenuItem1);

        save_as.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        save_as.setText("save as");
        save_as.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_asActionPerformed(evt);
            }
        });
        jMenu1.add(save_as);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Undo");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Redo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        clear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jMenu2.add(clear);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Window");

        onTop.setSelected(true);
        onTop.setText("Always On Top");
        onTop.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                onTopStateChanged(evt);
            }
        });
        jMenu3.add(onTop);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(xP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xPos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(yP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yPos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clear_button)
                        .addGap(19, 19, 19)
                        .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(paintPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(colorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(penSize, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paintPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(yP)
                                    .addComponent(xP)
                                    .addComponent(xPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(clear_button)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(colorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(penSize, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorLabelMouseClicked
        // TODO add your handling code here:
        color = JColorChooser.showDialog(this, "Choose Color", color);
        if(color != null){
            graphics.setPaint(color);
            colorLabel.setBackground(color);
        }
        sizeStateChanged(null);
    }//GEN-LAST:event_colorLabelMouseClicked
    private int srcX = -1;
    private int srcY = -1;
    private void paintPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paintPanelMouseClicked
        // TODO add your handling code here:
        Point p = evt.getPoint();
        paintPanelMouseMoved(evt);
        int dstX = p.x;
        int dstY = p.y;
       // graphics.drawOval(p.x, p.y, 10, 10);
        
       // System.out.println(srcX +"   "+ srcY+"   "+p.x+"   "+ p.y);
        
        int si = size.getValue()+8;
        if(pencil.isSelected()){
            graphics.fillOval(p.x-(si/2), p.y-(si/2), si,si);
        }
        else if(line.isSelected()){
            if(srcX > -1){
                graphics.drawLine(srcX , srcY,p.x, p.y);
                srcX = -1;
                srcY = -1;
            }else{
                srcX = p.x;
                srcY = p.y;
            }
        }else if(eclipse.isSelected()){
             if(srcX > -1){
                int x_delta = dstX - srcX;
                int y_delta = dstY - srcY;
                if(x_delta < 0){
                    x_delta *= -1;
                    srcX = dstX;
                }if(y_delta < 0){
                    y_delta *= -1;
                    srcY = dstY;
                }
                if(fill.isSelected()){
                    graphics.fillOval(srcX , srcY,x_delta,y_delta);
                }
                else{
                    graphics.drawOval(srcX , srcY,x_delta,y_delta);
                }
                srcX = -1;
                srcY = -1;
            }else{
                srcX = p.x;
                srcY = p.y;
            }
        }else if(rectangle.isSelected()){
            if(srcX > -1){
                int x_delta = dstX - srcX;
                int y_delta = dstY - srcY;
                if(x_delta < 0){
                    x_delta *= -1;
                    srcX = dstX;
                }if(y_delta < 0){
                    y_delta *= -1;
                    srcY = dstY;
                }
                if(fill.isSelected()){
                    graphics.fillRect(srcX , srcY,x_delta,y_delta);
                }
                else{
                    graphics.drawRect(srcX , srcY,x_delta,y_delta);
                }
                //graphics.drawRect(srcX , srcY,p.x, p.y);
                srcX = -1;
                srcY = -1;
            }else{
                srcX = p.x;
                srcY = p.y;
            }
        }else if(text.isSelected()){
           // String textv = JOptionPane.showInputDialog(this, "Enter Text: ");
           // graphics.setFont(new Font("Old English", si, si));
           // graphics.drawString(textv, dstX, dstY);
            srcX = p.x;
            srcY = p.y;
            text_value.setText("");
            Graphics.setToCenter(this, fontFormat);
            fontFormat.setVisible(true);
            text_value.grabFocus();
        }
        else{
            graphics.setPaint(Color.white);
            graphics.fillOval(p.x-(si/2), p.y-(si/2), si,si);
            graphics.setPaint(color);
        }
        
        updateImage();
    }//GEN-LAST:event_paintPanelMouseClicked

    private void paintPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paintPanelMouseMoved
        // TODO add your handling code here:
        Point p = evt.getPoint();
        xPos.setText(p.x+"");
        yPos.setText(p.y+"");
    }//GEN-LAST:event_paintPanelMouseMoved

    private void paintPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paintPanelMouseDragged
        // TODO add your handling code here:
        paintPanelMouseClicked(evt);
    }//GEN-LAST:event_paintPanelMouseDragged

    private void save_asActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_asActionPerformed
        // TODO add your handling code here:
        JFileChooser jf = new JFileChooser(System.getProperty("user.home"));
        jf.showSaveDialog(this);
        if(jf.getSelectedFile() != null){
            String name = jf.getSelectedFile().getAbsolutePath();
            if(name.contains(".jpg")){
//                /int index = name.lastIndexOf(".jpg");
            }
            File path = new File(name);
            try {
                path.createNewFile();
                ImageIO.write(image, "jpeg", path);
            } catch (IOException ex) {
               // Logger.getLogger(PaintFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error on saving...", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_save_asActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
       
        image = new BufferedImage(paintPanel.getWidth(), paintPanel.getHeight(),BufferedImage.TYPE_INT_RGB);
        graphics = image.createGraphics(); 
        graphics.setPaint(Color.WHITE);
        graphics.fillRect(0, 0, paintPanel.getWidth(), paintPanel.getHeight());
        graphics.setPaint(color);
        updateImage();
        
    }//GEN-LAST:event_clearActionPerformed

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        // TODO add your handling code here:
        clearActionPerformed(evt);
    }//GEN-LAST:event_clear_buttonActionPerformed
    
    private void sizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sizeStateChanged
        // TODO add your handling code here:
        BufferedImage im = new BufferedImage(penSize.getWidth(), penSize.getHeight(), BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = im.createGraphics();
        g2.setColor(color);
        int px_size = size.getValue()+8;
        sizeLabel.setText(px_size+"");
        int x = (penSize.getWidth() - px_size) / 2;
        int y = (penSize.getHeight() - px_size) / 2;
        g2.fillOval(x, y, px_size, px_size);
        penSize.setIcon(new ImageIcon(im));
    }//GEN-LAST:event_sizeStateChanged

    private void paintPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paintPanelMouseEntered
        // TODO add your handling code here:
        if(pencil.isSelected()){
            paintPanel.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
        }else if(line.isSelected()){
            paintPanel.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
        }else if(eclipse.isSelected()){
            paintPanel.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
        }else if(rectangle.isSelected()){
            paintPanel.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
        }
        else if(text.isSelected()){
            paintPanel.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        }
        else{
            paintPanel.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
        }
    }//GEN-LAST:event_paintPanelMouseEntered

    private void onTopStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_onTopStateChanged
        // TODO add your handling code here:
        this.setAlwaysOnTop(onTop.isSelected());
    }//GEN-LAST:event_onTopStateChanged

    private void sizes_comboInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_sizes_comboInputMethodTextChanged
        // TODO add your handling code here:
        text_valueKeyTyped(null);
    }//GEN-LAST:event_sizes_comboInputMethodTextChanged

    private void sizes_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizes_comboActionPerformed
        // TODO add your handling code here:
        text_valueKeyTyped(null);
    }//GEN-LAST:event_sizes_comboActionPerformed

    private void font_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_font_nameActionPerformed
        // TODO add your handling code here:
        text_valueKeyTyped(null);
    }//GEN-LAST:event_font_nameActionPerformed

    private void italic_fontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italic_fontActionPerformed
        // TODO add your handling code here:
        text_valueKeyTyped(null);
    }//GEN-LAST:event_italic_fontActionPerformed

    private void bold_fontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bold_fontActionPerformed
        // TODO add your handling code here:
        text_valueKeyTyped(null);
    }//GEN-LAST:event_bold_fontActionPerformed
    Font text_font;
    private void text_valueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_valueKeyTyped
        // TODO add your handling code here:
        // TODO add your handling code here:
        int style = Font.PLAIN;
        if(italic_font.isSelected()){
            style = Font.ITALIC;
        }if(bold_font.isSelected()){
            style = Font.BOLD;
        }if(italic_font.isSelected() && bold_font.isSelected()){
            style = Font.BOLD | Font.ITALIC;
        }
        text_font = new Font(font_name.getSelectedItem().toString(), style,Integer.parseInt(sizes_combo.getSelectedItem().toString()));
        preview_text.setForeground(color);
        preview_text.setFont(text_font);
        String ff = text_value.getText();
        if(ff.length() > 15){
            ff = ff.substring(0,15);
        }
        preview_text.setText(ff);
    }//GEN-LAST:event_text_valueKeyTyped

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:
        graphics.setFont(text_font);
        graphics.drawString(text_value.getText(), srcX, srcY);
        fontFormat.setVisible(false);
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaintFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaintFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaintFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaintFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PaintFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bold_font;
    private javax.swing.JMenuItem clear;
    private javax.swing.JButton clear_button;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JRadioButton eclipse;
    private javax.swing.JRadioButton eraser;
    private javax.swing.JRadioButton fill;
    private javax.swing.JDialog fontFormat;
    private javax.swing.JComboBox font_name;
    private javax.swing.JCheckBox italic_font;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JRadioButton line;
    private javax.swing.JCheckBoxMenuItem onTop;
    private javax.swing.JRadioButton outline;
    private javax.swing.JLabel paintPanel;
    private javax.swing.JLabel penSize;
    private javax.swing.JRadioButton pencil;
    private javax.swing.JLabel preview_text;
    private javax.swing.JRadioButton rectangle;
    private javax.swing.JMenuItem save_as;
    private javax.swing.JSlider size;
    private javax.swing.JTextField sizeLabel;
    private javax.swing.JComboBox sizes_combo;
    private javax.swing.JRadioButton text;
    private javax.swing.JTextField text_value;
    private javax.swing.JLabel xP;
    private javax.swing.JTextField xPos;
    private javax.swing.JLabel yP;
    private javax.swing.JTextField yPos;
    // End of variables declaration//GEN-END:variables
}
